require("plugins.kanagawa")
require("plugins.lualine")
--require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.treesitter")
require("plugins.lsp-zero")
require("plugins.formatter")
require("plugins.netrw")
require("plugins.devicons")
require("plugins.mason")
require("plugins.vimtex")
require("plugins.yanky")
require("plugins.nvim-lint")
require("plugins.conform")
-- require("plugins.trouble")
